name: Post from Bluesky Bots

on:
    workflow_dispatch:
        inputs:
            country:
                description: "Country to post for"
                required: true
                type: choice
                options:
                    - Israel
                    - Canada

jobs:
    post-tweet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT_TOKEN }}
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
            - run: npm ci
            - name: Build TypeScript
              run: npm run build
            - name: Post to Bluesky
              env:
                  BLUESKY_HANDLE: ${{ secrets[format('{0}_BLUESKY_HANDLE', inputs.country)] }}
                  BLUESKY_PASSWORD: ${{ secrets[format('{0}_BLUESKY_PASSWORD', inputs.country)] }}
              run: npm run post ${{ inputs.country }}
            - name: Commit updated position
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add ${{ inputs.country }}/current_position.txt
                  git commit -m "Update current position for ${{ inputs.country }}" || echo "No changes to commit"
                  git push
