name: Schedule Canada Posts

on:
    schedule:
        - cron: "0 12,23 * * *"
    workflow_dispatch:

jobs:
    trigger-canada:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Canada workflow
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: Post from Bluesky Bots
                  token: ${{ secrets.PAT_TOKEN }}
                  inputs: '{"country": "Canada"}'
