name: Schedule Israel Posts

on:
    schedule:
        - cron: "0 6,17 * * *"
    workflow_dispatch:

jobs:
    trigger-israel:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Israel workflow
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: Post from Bluesky Bots
                  token: ${{ secrets.PAT_TOKEN }}
                  inputs: '{"country": "Israel"}'
